motosmexico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('orders_entry.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders_entry/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'orders_entry'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^nueva-orden/$', views.new_order, name='new_order'),
    url(r'^pdf/$', GeneratePDF.as_view(), name='pdf'),
]

clients/models.py
from django.db import models


class MotorcycleOwner(models.Model):
    responsible = models.CharField(max_length=120, blank=True, null=True)
    name = models.CharField(max_length=75, default='')
    last_name = models.CharField(max_length=120, default='')
    address = models.CharField(max_length=120, default='')
    colony = models.CharField(max_length=120, default='')
    rfc = models.CharField(max_length=13, unique=True, blank=True, null=True)
    postal_code = models.CharField(max_length=5, default='')
    email = models.EmailField(blank=True, null=True)
    city = models.CharField(max_length=72, default='')
    phone_1 = models.CharField(max_length=14, default='')
    phone_2 = models.CharField(max_length=14, default='')

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return '%s' % self.name

motorcycles/models.py
from django.db import models

from orders_entry.models import EntryOrder


class MotorclycleBrand(models.Model):
    brand = models.CharField(max_length=48, default='', unique=True)

    class Meta:
        verbose_name = "Marca de la Moto"
        verbose_name_plural = "Marcas de Motos"

    def __str__(self):
        return '%s' % self.brand


class MotorcycleModel(models.Model):
    model = models.CharField(max_length=92, default='', unique=True)
    brand = models.ForeignKey(MotorclycleBrand)

    class Meta:
        verbose_name = "Modelo de Moto"
        verbose_name_plural = "Modelos de Motos"

    def __str__(self):
        return '%s' % self.model


class MotorcycleClient(models.Model):
    model = models.ForeignKey(MotorcycleModel)
    version = models.CharField(max_length=45, default='')
    plates = models.CharField(max_length=12, default='')
    vin = models.CharField(max_length=18, default='')
    engine_number = models.CharField(max_length=18, default='')
    year = models.CharField(max_length=4, default='2000')

    class Meta:
        verbose_name = "Moto"
        verbose_name_plural = "Motos"

    def __str__(self):
        return '%s' % self.entry_order

    def model(self):
        return '%s - %s' % (self.model.brand, self.model)


class MotorcycleRegion(models.Model):
    name = models.CharField(max_length=72, default='')

    class Meta:
        verbose_name = 'Región de la Moto'
        verbose_name_plural = 'Regiones de la Moto'

    def __str__(self):
        return '%s' % self.name


class MotorcycleDamages(models.Model):
    entry_order = models.OneToOneField(
        EntryOrder,
        primary_key=True,
        on_delete=models.CASCADE,
    )
    observations = models.TextField(default='Ninguna')

    class Meta:
        verbose_name = 'Daños de la moto'
        verbose_name_plural = 'Daños de las motos'

    def __str__(self):
        return '%s' % self.entry_order


class StatusTyre(models.Model):
    QUART = 'Q'
    MIDDLE = 'M'
    ENTIRE = 'E'

    LIFETIME_CONDITION = (
        (QUART, '1/4'),
        (MIDDLE, '1/2'),
        (ENTIRE, '1/1'),
    )

    RIM_OPTION = (
        ('A', 'A'),
        ('R', 'R'),
    )
    position = models.CharField(max_length=2)
    rim = models.CharField(choices=RIM_OPTION, default='A', max_length=1)
    lifetime = models.CharField(choices=LIFETIME_CONDITION, default=ENTIRE, max_length=1)
    condition = models.TextField()
    brand = models.CharField(max_length=45)
    motorcycle_damages = models.ForeignKey(MotorcycleDamages)

    class Meta:
        verbose_name = 'Estado de la llanta'
        verbose_name_plural = 'Estado de las llantas'

    def __str__(self):
        return '%s' % self.pk


class StatusGroup(models.Model):
    A = 'SNC'
    B = '124'
    OPTIONS = (
        (A, 'Si - No- C/D'),
        (B, '1/4 - 1/2 - 1/1'),
    )
    alias = models.CharField(choices=OPTIONS,max_length=3, default=A, unique=True)

    class Meta:
        verbose_name = 'Grupo de Condiciones'
        verbose_name_plural = 'Grupos de Condiciones'

    def __str__(self):
        return '%s' % self.alias


class Status(models.Model):
    status = models.CharField(max_length=12)
    group = models.ForeignKey(StatusGroup)

    class Meta:
        verbose_name = 'Condición'
        verbose_name_plural = 'Condiciones'

    def __str__(self):
        return '%s' % self.status



class MotorcyclePart(models.Model):
    name = models.CharField(max_length=72, default='')
    motorcycle_region = models.ForeignKey(MotorcycleRegion)
    status_group = models.ForeignKey(StatusGroup)

    class Meta:
        verbose_name = "Parte de la Moto"
        verbose_name_plural = "Partes de la Moto"

    def __str__(self):
        return '%s' % self.name


class StatusMotorcyclePart(models.Model):
    motorcycle_damages = models.ForeignKey(MotorcycleDamages)
    motorcycle_part = models.ForeignKey(MotorcyclePart, on_delete=models.CASCADE)
    status = models.ForeignKey(Status)

    class Meta:
        verbose_name = 'Estado de Pieza'
        verbose_name_plural = 'Estado de Piezas'

    def __str__(self):
        return '%s' % self.pk

orders_entry/models.py
from django.db import models
from clients.models import MotorcycleOwner


class EntryOrder(models.Model):
    order = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now=True)
    on_tow = models.BooleanField(default=True)
    motorcycle_owner = models.ForeignKey(MotorcycleOwner)
    # adviser  FK
    # appraiser FK

    class Meta:
        verbose_name = 'Órden de entrada'
        verbose_name_plural = 'Órdenes de entrada'

    def __str__(self):
        return '%s' % self.order


class Sinister(models.Model):
    entry_order = models.OneToOneField(
        EntryOrder,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    sinister = models.CharField(max_length=14, default='')
    insurance_carrier = models.CharField(max_length=72, default='')
    policy = models.CharField(max_length=14, default='')
    deductible = models.DecimalField(max_digits=13, decimal_places=4, default=0)
    is_secured = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Siniestro'
        verbose_name_plural = 'Siniestros'

    def __str__(self):
        return '%s' % self.sinister

scheduler/models.py
from django.db import models

# Create your models here.

orders_entry/views.py
# import json
from django.shortcuts import render
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.generic import View

from motosmexico.reportpdf import render_pdf
from motorcycles.models import MotorcycleRegion, MotorcyclePart


def home(request):
    template = 'index.html'
    context = {}
    if request.method == 'POST':
        return JsonResponse({'result': '1'})
    return render(request, template, context)


def new_order(request):
    if request.method == 'POST':
        print(request.POST)
    template = 'new_order.html'
    motrocycle_regions = MotorcycleRegion.objects.all()
    motorcycle_parts = MotorcyclePart.objects.all()
    context = {
     'regions': motrocycle_regions,
     'parts': motorcycle_parts,
    }
    return render(request, template, context)


class GeneratePDF(View):
    """
    Return PDF create to base to a template
    """
    def get(self, request, *args, **kwargs):
        context = {}
        pdf = render_pdf('report.html', context)
        return HttpResponse(pdf, content_type='application/pdf')

scheduler/views.py
from django.shortcuts import render

# Create your views here.

motosmexico/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <!-- Title -->
  <title>Motos Mexico</title>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon -->
  <link rel="icon" type="image/png" href="{% static 'images/logo_ov.png' %}">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- Master CSS -->
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
  <!-- Entypo icons -->
  <link rel="stylesheet" href="{% static 'css/entypo-icons.css' %}">
</head>
<body>
  <header class="navbar navbar-expand-lg navbar-light bg-light shadow">
    <nav class="container">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/logo_ov.png' %}" height="35" class="d-inline-block align-top" alt="">
        <span class="navbar-title">
          Motos México Satélite
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders_entry:new_order' %}">Orden de Ingreso</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <!-- jQuery svgInject -->
  <script src="{% static 'js/jquery.svgInject.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $('.svg-inject').svgInject();
    });

  </script>
  {% block scripts %}
  {% endblock %}
  <!--
  <script type="text/javascript" src="http://localhost:35729/livereload.js"></script>
  -->
</body>
</html>

orders_entry/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-2">
  <div class="logo-container">
    <img src="{% static 'images/logo_ov.png' %}" alt="">
  </div>


</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {

  /**
   * Gets the csrf cookie from cache
   */
  function get_cookie(name) {
    var cookie_value = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookie_value = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookie_value;
  }

  var csrftoken = get_cookie('csrftoken');

  // $('.btn').click(function(event) {
  //   let idButton = $(this).attr('id');
  //   idButton = idButton.split('-')[1];
  //   console.log(idButton);
  // });
  //
  function prueba(id, name) {
    // console.log(id);
    // console.log(name);
    $.ajax({
      url: "{% url 'orders_entry:home' %}",
      type: 'POST',
      data: {
        // 'id': id,
        // 'name': name,
        'csrfmiddlewaretoken': csrftoken,
      },
      dataType: 'jsonp',
      traditional: true,
      success: function(result) {
        console.log('exito');
      },
    });
  }
  $('.btn').click(function(event) {
    let id = $(this).parent().siblings('.td-id').text();
    let name = $(this).parent().siblings('.td-name').text();
    prueba(id, name);
  });
});

</script>
{% endblock %}

orders_entry/templates/new_order.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <form id="new-order-form" class="form" action="" method="post">
    <h1 class="text-uppercase text-center">Orden de Ingreso</h1>
    <!-- progress -->
    <div class="progress-container shadow">
      <ul id="progress">
        {% for region in regions %}
        <li class="progress-item">
          <span>{{ region }}</span>
        </li>
        {% endfor %}
        <li>
          <span>Llantas</span>
        </li>
      </ul>
    </div>
    {% csrf_token %}

    <!-- FIELSETS FOR MOTORCYCLE PARTS -->
    {% for region in regions %}
    <fieldset class="form-group shadow">
      <legend>
        <span class="number"></span>
        {{ region }}
      </legend>

      <div class="row form-options">
        {% for part in parts %}
        {% if part.motorcycle_region == region %}
        <div id="opt-{{part.id}}" class="col col-12 col-md-6">
          <div class="radio-group" hidden>
            <input id="radio-{{part.id}}-1" type="radio" name="radio-{{part.id}}" value="1" checked>
            <input id="radio-{{part.id}}-2" type="radio" name="radio-{{part.id}}" value="2">
            <input id="radio-{{partid}}-3" type="radio" name="radio-{{part.id}}" value="3">
          </div>
          <div class="row opts-container">
            <button type="button" class="btn btn-outline-secondary btn-option col">
              {{ part }}
            </button>
            <div class="icon-option invisible rounded-circle">
              <img src="{% static 'icons/Entypo+/Entypo+/camera.svg' %}" class="svg-inject svg-light" alt="camera icon">
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>

      <div class="row fieldset-btns">
        <input type="button" name="previous" class="btn btn-primary previous action-button" value="Anterior">
        <input type="button" name="next" class="btn btn-primary next action-button" value="Siguiente">
      </div>

    </fieldset>
    {% endfor %}

    <!-- TYRE FIELDSET -->
    <fieldset class="form-group shadow">
      <legend>
        <span class="number"></span>
        Llantas
      </legend>

      <!-- Left Tyre -->
      <div class="row form-options">
        <div class="col-12 text-center">
          <h5 class="light">Llanta Izquierda</h5>
        </div>
        <div id="opt-9-2" class="col">
          <div class="radio-group" hidden>
            <input id="radio-ltyre-1" type="radio" name="radio-ltyre-life" value="1" checked>
            <input id="radio-lyre-2" type="radio" name="radio-ltyre-life" value="2">
            <input id="radio-ltyre-3" type="radio" name="radio-ltyre-life" value="3">
          </div>

          <div class="row opts-container">
            <div class="col-6 col-md-4 life-tyre-container mb-1">
              <label for="left-tyre-indicator" class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="left-tyre-indicator" id="left-tyre-indicator" checked>
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">Hay llanta</span>
              </label>
            </div>

            <div class="col-6 col-md-4 rim-tyre-container mb-2">
              <label>Rin</label>
              <label for="ltyre-rim-A" class="custom-control custom-radio">
                <input type="radio" name="ltyre-rim" value="A" class="custom-control-input" id="ltyre-rim-A" checked>
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">A</span>
              </label>
              <label for="ltyre-rim-B" class="custom-control custom-radio">
                <input type="radio" name="ltyre-rim" value="B" class="custom-control-input" id="ltyre-rim-B">
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">B</span>
              </label>
            </div>

            <button type="button" class="btn btn-outline-secondary btn-option col-12 col-md-4 mb-2">
              Vida Llanta Izquierda
            </button>
            <div class="icon-option invisible rounded-circle">
              <img src="{% static 'icons/Entypo+/Entypo+/camera.svg' %}" class="svg-inject svg-light" alt="camera icon">
            </div>
          </div>
          <div class="row mt-2">
            <div class="form-group col-md-6">
              <label for="ltyre-condition">Condición</label>
              <input type="text" name="ltyre-condition" placeholder="Condición" id="ltyre-condition" class="form-control">
            </div>
            <div class="form-group col-md-6">
              <label for="ltyre-brand">Marca</label>
              <input type="text" name="ltyre-brand" placeholder="Marca" id="ltyre-condition" class="form-control">
            </div>
          </div>
        </div>
      </div>


          <!-- Right Tyre -->
          <div class="row form-options">
            <div class="col-12 text-center">
              <h5 class="light">Llanta Derecha</h5>
            </div>
            <div id="opt-9-2" class="col">
              <div class="radio-group" hidden>
                <input id="radio-rtyre-1" type="radio" name="radio-rtyre-life" value="1" checked>
                <input id="radio-ryre-2" type="radio" name="radio-rtyre-life" value="2">
                <input id="radio-rtyre-3" type="radio" name="radio-rtyre-life" value="3">
              </div>

              <div class="row opts-container">
                <div class="col-6 col-md-4 life-tyre-container mb-1">
                  <label for="right-tyre-indicator" class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" name="right-tyre-indicator" id="right-tyre-indicator" checked>
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">Hay llanta</span>
                  </label>
                </div>

                <div class="col-6 col-md-4 rim-tyre-container mb-2">
                  <label>Rin</label>
                  <label for="rtyre-rim-A" class="custom-control custom-radio">
                    <input type="radio" name="rtyre-rim" value="A" class="custom-control-input" id="rtyre-rim-A" checked>
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">A</span>
                  </label>
                  <label for="rtyre-rim-B" class="custom-control custom-radio">
                    <input type="radio" name="rtyre-rim" value="B" class="custom-control-input" id="rtyre-rim-B">
                    <span class="custom-control-indicator"></span>
                    <span class="custom-control-description">B</span>
                  </label>
                </div>

                <button type="button" class="btn btn-outline-secondary btn-option col-12 col-md-4 mb-2">
                  Vida Llanta Derecha
                </button>
                <div class="icon-option invisible rounded-circle">
                  <img src="{% static 'icons/Entypo+/Entypo+/camera.svg' %}" class="svg-inject svg-light" alt="camera icon">
                </div>
              </div>

              <div class="row mt-2">
                <div class="form-group col-md-6">
                  <label for="rtyre-condition">Condición</label>
                  <input type="text" name="rtyre-condition" placeholder="Condición" id="rtyre-condition" class="form-control">
                </div>
                <div class="form-group col-md-6">
                  <label for="rtyre-brand">Marca</label>
                  <input type="text" name="rtyre-brand" placeholder="Marca" id="rtyre-condition" class="form-control">
                </div>
              </div>
            </div>
          </div>

          <div class="row fieldset-btns">
            <input type="button" name="previous" class="btn btn-primary previous action-button" value="Anterior">
            <input type="button" name="finish" class="btn btn-primary finish action-button" value="Finalizar">
          </div>

        </fieldset>
      </form>
    </div>
    {% endblock %}

    {% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" integrity="sha256-H3cjtrm/ztDeuhCN9I4yh4iN2Ybx/y1RM7rMmAesA0k=" crossorigin="anonymous"></script>
    <script type="text/javascript">
    $(document).ready(function() {
      let current_fs,
      next_fs,
      previous_fs,
      lengthFieldsets;

      $('.btn-option').click(function(event) {
        let radioGroup = $(this).parent().siblings('.radio-group');
        let radioChecked = radioGroup.find('input[type=radio]:checked');
        let option = radioGroup.find('input[type=radio]:checked').val();
        let iconPhoto = $(this).siblings('.icon-option');

        if ( option === '1' ) {
          radioChecked.attr('checked',false);
          radioGroup.find('input:radio[value=2]').attr('checked', 'checked');
          $(this).addClass('active');
          $(this).removeClass('btn-outline-secondary');
          $(this).addClass('btn-warning');
          iconPhoto.removeClass('invisible')

        } else if ( option === '2' ) {
          radioChecked.attr('checked',false);
          radioGroup.find('input:radio[value=3]').attr('checked', 'checked');
          $(this).removeClass('btn-warning');
          $(this).addClass('btn-danger');

        } else {
          radioChecked.attr('checked',false);
          radioGroup.find('input:radio[value=1]').attr('checked', 'checked');
          $(this).removeClass('active');
          $(this).removeClass('btn-danger');
          $(this).addClass('btn-outline-secondary');
          iconPhoto.addClass('invisible')
        }
      });


      $(".next").click(function(){
        current_fs = $(this).parents('fieldset');
        next_fs = $(this).parents('fieldset').next();
        $("#progress li").eq($("fieldset").index(next_fs)).addClass("active");

        next_fs.show();
        // Hide actual fieldset
        current_fs.animate({opacity: 0}, {
          step: function(now, mx) {
            // 1. Scale current_fs up to 80%
            scale = 1 - (1 - now) * 0.2;
            // 2. Bring next_fs from the right (50%)
            left = (now * 50)+"%";
            // 3. Increase opacity of next_fs a 1 as it progresses
            opacity = 1 - now;
            current_fs.css({'transform': 'scale('+scale+')'});
            next_fs.css({'left': left, 'opacity': opacity});
          },
          duration: 800,
          complete: function(){
            current_fs.hide();
          },
          //Esto viene del plugin easing
          easing: 'easeInOutBack'
        });

      });

      $(".previous").click(function(){
        current_fs = $(this).parents('fieldset');
        previous_fs = $(this).parents('fieldset').prev();

        // Un-active actual progress step
        $("#progress").find("li").eq($("fieldset").index(current_fs)).removeClass("active");

        // Show the last fieldset
        previous_fs.show();
        // Hide the actual fieldset with style
        current_fs.animate({opacity: 0}, {
          step: function(now, mx) {
            var scale,
            left,
            opacity;
            // As the opacity of current_fs reduces to 0 - stored in "now"
            // 1. Scale previous_fs de 80% a 100%
            scale = 0.8 + (1 - now) * 0.2;
            // 2. take current_fs to the right(50%) - from 0%
            left = ((1 - now) * 50) + "%";
            // 3. increase opacity of previous_fs to 1 as it moves in
            opacity = 1 - now;
            current_fs.css({'left': left});
            previous_fs.css({'transform': 'scale('+scale+')', 'opacity': opacity});
          },
          duration: 800,
          complete: function(){
            current_fs.hide();
          },
          easing: 'easeInOutBack'
        });
      });

      /** Set number fields */
      $('.number').each(function (count) {
        $(this).text(count + 1);
      });

      /** Set first active class to progress items */
      $('li.progress-item').each(function(index, el) {
        $(this).addClass('active');
        return false;
      });

      /** Set hidden attribute to the corresponding buttons */
      lengthFieldsets = $('.fieldset-btns').length;
      $('.fieldset-btns').each(function(index, el) {
        if (index === 0) {
          $(this).find('input.previous').attr('type', 'hidden');
        }
        if (index === lengthFieldsets) {
          $(this).find('input.next').attr('type', 'hidden');
        }
      });
    });

    </script>
    {% endblock %}